# Site settings
title: Lunatic's Anecdotes
email: varunwachaspati@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Librocubicularist, Enchanted Dreamer, Ocassionally Code
  
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: varunwachaspati
github_username:  varunwachaspati

# Build settings
markdown: kramdown
