# Dependencies
markdown:            redcarpet
highlighter:         pygments

# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Site settings
title: Destined Fanatism
email: varunwachaspati@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Whereabouts of the renowned boredom slayer and his escapades
baseurl: "~/blog/" # the subpath of your site, e.g. /blog/
url: "http://varunwachaspati.github.io" # the base hostname & protocol for your site
twitter_username: varunwachaspati
github_username:  varunwachaspati

paginate:            5

# Custom vars
version:             1.0.0
# Server
destination:	_gh_pages
host:	0.0.0.0
port:	9001
encoding:	UTF-8