# Site settings
title: Destined Fanatism
email: varunwachaspati@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Whereabouts of the renowned boredom slayer and his escapades
baseurl: "~/blog/" # the subpath of your site, e.g. /blog/
url: "http://varunwachaspati.github.io" # the base hostname & protocol for your site
twitter_username: varunwachaspati
github_username:  varunwachaspati

# Build settings
markdown: kramdown

# Dependencies
markdown:	rdiscount
pygments:	true

# Permalinks
permalink:	pretty

# Server
destination:	_gh_pages
host:	0.0.0.0
port:	9001
encoding:	UTF-8
